//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework.api.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit
    {
        public int Id { get; set; }
        public string Reference { get; set; }
        public string Designation { get; set; }
        public string PrixUnitaire { get; set; }
        public System.DateTime DateCreation { get; set; }
        public System.DateTime DatePeremption { get; set; }
        public string Description { get; set; }
        public bool Status { get; set; }
        public int QuantiteStock { get; set; }
        public int IdCategorie { get; set; }
    
        public virtual Categorie Categorie { get; set; }
    }
}
